# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./api/src:/app
      - ./plugin/src/grpc-web-client:/grpc-web-client