// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: translator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TranslatorServiceClient is the client API for TranslatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslatorServiceClient interface {
	Translator(ctx context.Context, opts ...grpc.CallOption) (TranslatorService_TranslatorClient, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type translatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslatorServiceClient(cc grpc.ClientConnInterface) TranslatorServiceClient {
	return &translatorServiceClient{cc}
}

func (c *translatorServiceClient) Translator(ctx context.Context, opts ...grpc.CallOption) (TranslatorService_TranslatorClient, error) {
	stream, err := c.cc.NewStream(ctx, &TranslatorService_ServiceDesc.Streams[0], "/translator.TranslatorService/Translator", opts...)
	if err != nil {
		return nil, err
	}
	x := &translatorServiceTranslatorClient{stream}
	return x, nil
}

type TranslatorService_TranslatorClient interface {
	Send(*TranslatorRequest) error
	Recv() (*TranslatorResponse, error)
	grpc.ClientStream
}

type translatorServiceTranslatorClient struct {
	grpc.ClientStream
}

func (x *translatorServiceTranslatorClient) Send(m *TranslatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translatorServiceTranslatorClient) Recv() (*TranslatorResponse, error) {
	m := new(TranslatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *translatorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/translator.TranslatorService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslatorServiceServer is the server API for TranslatorService service.
// All implementations must embed UnimplementedTranslatorServiceServer
// for forward compatibility
type TranslatorServiceServer interface {
	Translator(TranslatorService_TranslatorServer) error
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedTranslatorServiceServer()
}

// UnimplementedTranslatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTranslatorServiceServer struct {
}

func (UnimplementedTranslatorServiceServer) Translator(TranslatorService_TranslatorServer) error {
	return status.Errorf(codes.Unimplemented, "method Translator not implemented")
}
func (UnimplementedTranslatorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTranslatorServiceServer) mustEmbedUnimplementedTranslatorServiceServer() {}

// UnsafeTranslatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslatorServiceServer will
// result in compilation errors.
type UnsafeTranslatorServiceServer interface {
	mustEmbedUnimplementedTranslatorServiceServer()
}

func RegisterTranslatorServiceServer(s grpc.ServiceRegistrar, srv TranslatorServiceServer) {
	s.RegisterService(&TranslatorService_ServiceDesc, srv)
}

func _TranslatorService_Translator_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslatorServiceServer).Translator(&translatorServiceTranslatorServer{stream})
}

type TranslatorService_TranslatorServer interface {
	Send(*TranslatorResponse) error
	Recv() (*TranslatorRequest, error)
	grpc.ServerStream
}

type translatorServiceTranslatorServer struct {
	grpc.ServerStream
}

func (x *translatorServiceTranslatorServer) Send(m *TranslatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translatorServiceTranslatorServer) Recv() (*TranslatorRequest, error) {
	m := new(TranslatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TranslatorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslatorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translator.TranslatorService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslatorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranslatorService_ServiceDesc is the grpc.ServiceDesc for TranslatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translator.TranslatorService",
	HandlerType: (*TranslatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TranslatorService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Translator",
			Handler:       _TranslatorService_Translator_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translator.proto",
}
