root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go mod tidy && protoc -I /app/proto --go_opt=module=voice-translator --go_out=. --go-grpc_opt=module=voice-translator --go-grpc_out=. --js_out=import_style=commonjs,binary:/grpc-web-client --grpc-web_out=import_style=typescript,mode=grpcwebtext:/grpc-web-client /app/proto/*.proto && go build -o ./tmp /app/cmd/api/main.go"
# cmd = "go mod tidy && go build -o ./tmp /app/cmd/api/main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", ".pb.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "proto"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
